import type { MetadataRoute } from "next";

// Web app manifest. The PWA icons reuse the 192/512 entries generated by
// app/icon.tsx so every icon size comes from the one transparent flag source.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Asmita Din 2026",
    short_name: "Asmita Din",
    description: "Event companion for Asmita Din 2026",
    start_url: "/",
    display: "standalone",
    background_color: "#faf7f2",
    theme_color: "#faf7f2",
    icons: [
      { src: "/icon/192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon/512", sizes: "512x512", type: "image/png", purpose: "any" },
    ],
  };
}
